[project]
name = "data4vlm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.3.0",
    "setuptools>=77.0.3",
    "streamlit>=1.42.0",
    "transformers>=4.48.3",
]
